# Generated by Django 5.2.3 on 2025-06-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('al', 'All Categories'), ('bi', 'Biography'), ('po', 'Poetry'), ('nv', 'Novel'), ('tr', 'Thriller'), ('dv', 'Devotional'), ('sr', 'Story'), ('ai', 'AutoBiography')], default='al', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
