# Generated by Django 5.2.3 on 2025-08-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_book_category_alter_book_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
